
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USER/YOUR_REPO
    targetRevision: main
    path: deploy/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
``
